### ISSUE TITLE
Count page cache in memory usage mistakenly

### ISSUE THREAD

**Issue by pzread** [pzread/judge#4]
Situation
====
"memory.max_usage_in_bytes" of cgroup includes the size of page cache consumed by the programs.
This will cause over-approximation of the memory usage.

**Comment by pzread** [comment]
commit 1ed83c6d37edd13bbd837d93fb358015b0094b0e fix this problem by O_DIRECT.
The performance will drop little.

**Comment by pzread** [comment]
Performance is unacceptable

**Comment by suhorng** [comment]
強強
